
-- CRIANDO A TABELA DE CLIENTES

CREATE TABLE CLIENTES (
	CPF VARCHAR(11),
	NOME VARCHAR(100),
	ENDEREÇO_1 VARCHAR(150),
	ENDEREÇO_2 VARCHAR(150),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	ESTADO VARCHAR(2),
	CEP VARCHAR(8),
	DATA_NASCIMENTO DATE,
	IDADE SMALLINT,
	SEXO VARCHAR(1),
	LIMITE_CREDITO MONEY,
	VOLUME_MINIMO_COMPRA FLOAT,
	PRIMEIRA_COMPRA BIT )


-- CRIANDO A TABELA DE VENDEDORES

CREATE TABLE VENDEDORES_2 (
	MATRICULA VARCHAR(5),
	NOME_VENDEDOR VARCHAR(100),
	PERCENTUAL_COMISSAO FLOAT )

-- CRIANDO A TABELA DE PRODUTOS (VAMOS CRIAR ATRAVÉS DO ASSISTENTE)

CREATE TABLE PRODUTOS (

COD_PRODUTO [varchar](10) NULL,
	[NOME_PRODUTO] [varchar](50) NULL,
	[EMBALAGEM] [varchar](20) NULL,
	[TAMANHO] [varchar](10) NULL,
	[SABOR] [varchar](20) NULL,
	[PRECO_LISTA] [smallmoney] NULL )


-- EXCLUINDO A TABELA

DROP TABLE VENDEDORES_2

-- INCLUINDO DADOS NA TABELA DE PRODUTOS

INSERT INTO PRODUTOS (
	COD_PRODUTO,
	NOME_PRODUTO,
	EMBALAGEM,
	TAMANHO,
	SABOR,
	PRECO_LISTA ) VALUES (
	'1040107','Light - 350 ml - Melância','Lata','350 ml','Melância',4.56
	)

INSERT INTO PRODUTOS (
	COD_PRODUTO,
	NOME_PRODUTO,
	EMBALAGEM,
	TAMANHO,
	SABOR,
	PRECO_LISTA ) VALUES (
	'1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.01
	)

INSERT INTO PRODUTOS (
	COD_PRODUTO,
	NOME_PRODUTO,
	EMBALAGEM,
	TAMANHO,
	SABOR,
	PRECO_LISTA ) VALUES (
	'1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.31
	)

INSERT INTO PRODUTOS (
	COD_PRODUTO,
	NOME_PRODUTO,
	EMBALAGEM,
	TAMANHO,
	SABOR,
	PRECO_LISTA ) VALUES (
	'544931','Frescor do Verão - 350 ml - Limão','Lata','350 ml','Limão',2.46
	)

INSERT INTO PRODUTOS (
	COD_PRODUTO,
	NOME_PRODUTO,
	EMBALAGEM,
	TAMANHO,
	SABOR,
	PRECO_LISTA ) VALUES (
	'1078680','Frescor do Verão - 470 ml - Manga','Garrafa','470 ml','Manga',5.18
	)


SELECT * FROM PRODUTOS


INSERT INTO VENDEDORES VALUES (
	'00233','José Geraldo da Fonseca',10)

INSERT INTO VENDEDORES VALUES (
	'00235','Márcio Almeida Silva',0.08)

INSERT INTO VENDEDORES VALUES (
	'00236','Cláudia Morais',0.08)

INSERT INTO VENDEDORES VALUES (
	'00237','Roberta Martins',0.11)

INSERT INTO VENDEDORES VALUES (
	'00238','Pericles Alves',0.07)


SELECT * FROM VENDEDORES
SELECT * FROM PRODUTOS
ORDER BY COD_PRODUTO

UPDATE VENDEDORES 
SET PERCENTUAL_COMISSAO = 0.10
WHERE MATRICULA = '00233'

UPDATE PRODUTOS
SET TAMANHO = 'Lata', PRECO_LISTA = 2.46
WHERE COD_PRODUTO = '544931'

UPDATE PRODUTOS
SET TAMANHO = 'Lata', PRECO_LISTA = 2.46
WHERE COD_PRODUTO = '544931'

DELETE FROM PRODUTOS
WHERE COD_PRODUTO = '1078680'

-- DESAFIO

 

UPDATE VENDEDORES
SET PERCENTUAL_COMISSAO = 0.11
WHERE MATRICULA = '00238'

UPDATE VENDEDORES
SET NOME_VENDEDOR = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233'

DELETE PRODUTOS
WHERE COD_PRODUTO = '1088126'

DELETE VENDEDORES
WHERE MATRICULA = '00233'

-- CHAVE PRIMÁRIA

INSERT INTO PRODUTOS 
VALUES (

	'788975','Pedaços de Frutas - 1,5 Litros - Maça','PET','1.5 Litros','Maçã',18.01)

SELECT * FROM PRODUTOS

DELETE FROM PRODUTOS
WHERE COD_PRODUTO = '788975'

-- COMO CRIAR UMA CHAVE PRIMÁRIA

ALTER TABLE PRODUTOS
ADD CONSTRAINT PK_PRODUTOS
PRIMARY KEY CLUSTERED (COD_PRODUTO)

-- ALTERANDO A COLUNA	

ALTER TABLE PRODUTOS
ALTER COLUMN COD_PRODUTO
VARCHAR(10) NOT NULL

SELECT * FROM CLIENTES

ALTER TABLE VENDEDORES
ALTER COLUMN MATRICULA
VARCHAR(5) NOT NULL

;
ALTER TABLE VENDEDORES
ADD CONSTRAINT PK_VENDEDORES
PRIMARY KEY CLUSTERED (MATRICULA)

ALTER TABLE CLIENTES
ALTER COLUMN CPF
VARCHAR(11) NOT NULL

;
 

INSERT INTO [dbo].[CLIENTES]
           ([CPF]
           ,[NOME_CLIENTE]
           ,[ENDEREÇO_1]
           ,[ENDEREÇO_2]
           ,[BAIRRO]
           ,[CIDADE]
           ,[ESTADO]
           ,[CEP]
           ,[DATA_NASCIMENTO]
           ,[IDADE]
           ,[SEXO]
           ,[LIMITE_CREDITO]
           ,[VOLUME_MINIMO_COMPRA]
           ,[PRIMEIRA_COMPRA])
     VALUES
           ('00300000001'
           ,'João da Silva'
           ,'Rua Projetada A número 10'
           ,''
           ,'Centro'
           ,'Rio de Janeiro'
           ,'RJ'
           ,'2000000'
           ,'1990-10-25'
           ,'27'
           ,'M'
           ,120000.50
           ,1000
           ,1)


select * from VENDEDORES

ALTER TABLE VENDEDORES
ADD DATA_ADMISSAO DATE

ALTER TABLE VENDEDORES
ADD FERIAS BIT

UPDATE VENDEDORES
SET DATA_ADMISSAO = '2014-08-15'
WHERE MATRICULA = '00235'

UPDATE VENDEDORES
SET DATA_ADMISSAO = '2013-09-17'
WHERE MATRICULA = '00236'

UPDATE VENDEDORES
SET DATA_ADMISSAO = '2017-03-18'
WHERE MATRICULA = '00237'

UPDATE VENDEDORES
SET DATA_ADMISSAO = '2016-08-21'
WHERE MATRICULA = '00238'

UPDATE VENDEDORES
SET FERIAS = 0
WHERE MATRICULA = '00235'

UPDATE VENDEDORES
SET FERIAS = 1
WHERE MATRICULA = '00236'

UPDATE VENDEDORES
SET FERIAS = 1
WHERE MATRICULA = '00237'

UPDATE VENDEDORES
SET FERIAS = 0
WHERE MATRICULA = '00238'


SELECT * FROM VENDEDORES WHERE UPPER(NOME_VENDEDOR) LIKE '%CLÁUDIA%'
SELECT * FROM VENDEDORES WHERE YEAR(DATA_ADMISSAO) >= 2016


-- ******************************** SEGUNDO CURSO *************************************



SELECT * FROM [TABELA DE PRODUTOS] WHERE 
[SABOR] = 'Manga' OR [TAMANHO] = '700 ml' 

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
[SABOR] = 'Manga' AND [TAMANHO] = '700 ml' 

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
NOT ([SABOR] = 'Manga' AND [TAMANHO] = '700 ml')

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
NOT ([SABOR] = 'Manga' OR [TAMANHO] = '700 ml')

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
[SABOR] = 'Manga' AND NOT ( [TAMANHO] = '700 ml')

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
[SABOR] IN ('Manga', 'Laranja')

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
[SABOR] = 'Manga' OR [SABOR] ='Laranja'

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
[SABOR] NOT IN ('Manga', 'Laranja')

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
NOT ([SABOR] = 'Manga' OR [SABOR] ='Laranja')

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
[SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] > 10

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
[SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] BETWEEN 10 AND 13

SELECT * FROM [TABELA DE PRODUTOS] WHERE 
[SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] >= 10 AND [PREÇO DE LISTA] <= 13


SELECT BAIRRO, COUNT(*) CONTAGEM FROM [TABELA DE CLIENTES] GROUP BY BAIRRO

SELECT DISTINCT BAIRRO, CIDADE FROM [TABELA DE CLIENTES] WHERE CIDADE = 'Rio de Janeiro'

SELECT BAIRRO, CIDADE, COUNT(*) CONTAGEM FROM [TABELA DE CLIENTES] 
WHERE CIDADE = 'Rio de Janeiro'
GROUP BY BAIRRO

SELECT NOME, [DATA DE NASCIMENTO],
CASE
	WHEN YEAR([DATA DE NASCIMENTO]) < 1990 THEN 'ADULTOS'
	WHEN YEAR([DATA DE NASCIMENTO]) BETWEEN 1990 AND 1995 THEN 'JOVENS'
	WHEN YEAR([DATA DE NASCIMENTO]) > 1995 THEN 'CRIANÇAS' 
	END AS CATEGORIA
FROM [TABELA DE CLIENTES]



 

SELECT A.NOME,COUNT(*) CONTAGEM, YEAR(B.DATA) ANO FROM [TABELA DE VENDEDORES] A
INNER JOIN [NOTAS FISCAIS] B ON A.MATRICULA = B.MATRICULA
GROUP BY A.NOME,YEAR(B.DATA)
ORDER BY NOME, ANO

SELECT * FROM [NOTAS FISCAIS]
SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT SUM(QUANTIDADE) QTDE_TOTAL,SUM(PREÇO) PREÇO_TOTAL,SUM(QUANTIDADE) * SUM(PREÇO) FROM [ITENS NOTAS FISCAIS]

SELECT YEAR(A.DATA) ANO,SUM(B.QUANTIDADE) * SUM(B.PREÇO) FROM [NOTAS FISCAIS] A
INNER JOIN [ITENS NOTAS FISCAIS] B ON A.NUMERO = B.NUMERO
GROUP BY YEAR(A.DATA)
ORDER BY YEAR(A.DATA)

SELECT YEAR(DATA), SUM (QUANTIDADE * [PREÇO]) AS FATURAMENTO
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
GROUP BY YEAR(DATA)

SELECT A.NOME,B.NUMERO FROM [TABELA DE CLIENTES] A
LEFT JOIN [NOTAS FISCAIS] B ON A.CPF = B.CPF
GROUP BY NOME,B.NUMERO
ORDER BY NUMERO